name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{matrix.image}}
      options: --privileged
    strategy:
      matrix:
        image: ['ubuntu', 'debian', 'debian:stretch', 'opensuse/leap']
      fail-fast: false

    steps:
      - name: Install dependencies (ubuntu / debian)
        if: startsWith(matrix.image, 'ubuntu') || startsWith(matrix.image, 'debian')
        run: apt update && apt install -y wget file dpkg-dev fuse g++ cmake qtbase5-dev libicu-dev libxdo-dev
        
      - name: Install dependencies (debian:stretch)
        if: startsWith(matrix.image, 'debian:stretch')
        run: apt install qt5-default
      
      - name: Install dependencies (opensuse/leap)
        if: startsWith(matrix.image, 'opensuse/leap')
        run: zypper install -y tar gzip wget rpm-build gcc-c++ cmake libqt5-qtbase-devel libicu-devel xdotool-devel
      
      - name: Install dependencies .AppImage
        if: startsWith(matrix.image, 'debian:stretch')
        run: |
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          cp ./linuxdeployqt-continuous-x86_64.AppImage /usr/bin/linuxdeployqt.AppImage
        
      - uses: actions/checkout@v2

      - name: Configure CMake (ubuntu / debian)
        if: startsWith(matrix.image, 'ubuntu') || startsWith(matrix.image, 'debian')
        env:
          CPACK_GENERATOR: DEB
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..

      - name: Configure CMake (opensuse/leap)
        if: startsWith(matrix.image, 'opensuse/leap')
        env:
          CPACK_GENERATOR: RPM
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..

      - name: Build
        run: |
          cd build
          make

      - name: Package
        if: "! endsWith(matrix.image, 'debian:stretch')"
        run: |
          cd build
          make package

      - name: Package .AppImage
        if: "endsWith(matrix.image, 'debian:stretch')"
        run: |
          cd build
          make appimage

      - name: Upload artifact .deb
        if: endsWith(matrix.image, 'ubuntu') || endsWith(matrix.image, 'debian')
        uses: actions/upload-artifact@v2.2.4
        with:
          name: x11-emoji-picker.x86_64-${{matrix.image}}.deb
          path: build/x11-emoji-picker-x86_64.deb

      - name: Upload artifact .rpm
        if: endsWith(matrix.image, 'opensuse/leap')
        uses: actions/upload-artifact@v2.2.4
        with:
          name: x11-emoji-picker.x86_64-opensuse.rpm
          path: build/x11-emoji-picker-x86_64.rpm

      - name: Upload artifact .AppImage
        if: endsWith(matrix.image, 'debian:stretch')
        uses: actions/upload-artifact@v2.2.4
        with:
          name: x11-emoji-picker-x86_64.AppImage
          path: build/x11-emoji-picker-dev-x86_64.AppImage

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/master')

    steps:
      - name: Create release
        id: create_release
        uses: pajlada/create-release@v2.0.3
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: nightly-build
          backup_tag_name: backup-nightly-build
          release_name: Nightly Release
          body: |
            Nightly Build
          prerelease: true

      - uses: actions/download-artifact@v2.0.10
        with:
          name: x11-emoji-picker-x86_64-ubuntu.deb
          path: linux-cmake/

      - name: Upload release asset (Ubuntu .deb)
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: linux-cmake/x11-emoji-picker-x86_64-ubuntu.deb
          asset_name: x11-emoji-picker-x86_64-ubuntu.deb
          asset_content_type: application/vnd.debian.binary-package

      - uses: actions/download-artifact@v2.0.10
        with:
          name: x11-emoji-picker-x86_64-debian.deb
          path: linux-cmake/

      - name: Upload release asset (Debian .deb)
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: linux-cmake/x11-emoji-picker-x86_64-debian.deb
          asset_name: x11-emoji-picker-x86_64-debian.deb
          asset_content_type: application/vnd.debian.binary-package

      - uses: actions/download-artifact@v2.0.10
        with:
          name: x11-emoji-picker-x86_64-opensuse.rpm
          path: linux-cmake/

      - name: Upload release asset (OpenSUSE .rpm)
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: linux-cmake/x11-emoji-picker-x86_64-opensuse.rpm
          asset_name: x11-emoji-picker-x86_64-opensuse.rpm
          asset_content_type: application/x-rpm

      - uses: actions/download-artifact@v2.0.10
        with:
          name: x11-emoji-picker-dev-x86_64.AppImage
          path: linux-cmake/

      - name: Upload release asset .AppImage
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: linux-cmake/x11-emoji-picker-dev-x86_64.AppImage
          asset_name: x11-emoji-picker-x86_64.AppImage
          asset_content_type: application/x-executable
